#!/bin/bash
# Put your own configuration here
# This file will be merged to the end of i3 config
# and will be ignored by git

function i3config(){
local mod='$mod'

cat << EOF
focus_follows_mouse no

# User defined keys
bindsym Print exec i3-scrot -d
bindsym Shift+Print exec i3-scrot -s
bindsym Mod1+Sys_Req exec i3-scrot -w
bindsym $mod+F1 exec --no-startup-id i3-sensible-terminal -e alsamixer
bindsym $mod+F2 exec --no-startup-id sensible-browser
bindsym $mod+F3 exec --no-startup-id i3-sensible-terminal -e ranger
bindsym $mod+F4 exec --no-startup-id galculator
bindsym $mod+F5 exec --no-startup-id i3-sensible-terminal -e cmus
EOF
}
