#!/bin/bash
# User's own configuration
# add your own modules here
# This file with be concatenated with the default file
# and thus it will be ignored bit git

function polybarConfig(){
cat << POLYBAR
[bar/i3wmthemer_bar]
width = 100%
height = 27
radius = 0
fixed-center = false

background = ${polybar['background']}
foreground = ${polybar['foreground']}

line-size = 3
line-color =

border-size = 0
border-color =

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = "Fira Code:style=semibold:size=10;1"
font-1 = "FontAwesome:size=10;1"

modules-left = ${polybar['modules-left']}
modules-center = ${polybar['modules-center']}
modules-right = ${polybar['modules-right']}

tray-position = none
;tray-padding =
;wm-restack = i3
override-redirect = false

cursor-click = pointer
cursor-scroll = ns-resize
POLYBAR
}
