#!/bin/bash
# User own configuration
# add here everything you want
function xresourcesConfig(){
cat << XRESOURCES
! https://github.com/majutsushi/urxvt-font-size
! URxvt.perl-ext-common: ...,font-size
XRESOURCES
}
