#!/bin/bash
function xresourcesConfig(){
cat << XRESOURCES
*background:                      ${xresources['background']}
*foreground:                      ${xresources['foreground']}
*cursorColor:                     ${xresources['cursorcolor']}

*color0:                          ${xresources['color0']}
*color8:                          ${xresources['color8']}
*color1:                          ${xresources['color1']}
*color9:                          ${xresources['color9']}
*color2:                          ${xresources['color2']}
*color10:                         ${xresources['color10']}
*color3:                          ${xresources['color3']}
*color11:                         ${xresources['color11']}
*color4:                          ${xresources['color4']}
*color12:                         ${xresources['color12']}
*color5:                          ${xresources['color5']}
*color13:                         ${xresources['color13']}
*color6:                          ${xresources['color6']}
*color14:                         ${xresources['color14']}
*color7:                          ${xresources['color7']}
*color15:                         ${xresources['color15']}

URxvt.font: xft:Source Code Pro:size=14
URxvt.depth:                      32
URxvt*scrollBar:                  false
URxvt*mouseWheelScrollPage:       false
URxvt*cursorBlink:                true
URxvt*saveLines:                  5000
URxvt*internalBorder: 5
URxvt*geometry: 70x19

rofi.color-enabled: true
rofi.color-window: ${xresources['rofi.color-window']}
rofi.color-normal: ${xresources['rofi.color-normal']}
rofi.color-active: ${xresources['rofi.color-active']}
rofi.color-urgent: ${xresources['rofi.color-urgent']}

rofi.separator-style: solid
rofi.sidebar-mode: false
rofi.lines: 5
rofi.font: Source Code Pro Bold 10.5
rofi.bw: 1
rofi.columns: 2
rofi.padding: 5
rofi.fixed-num-lines: true
rofi.hide-scrollbar: true

! Normal copy-paste keybindings without perls
URxvt.iso14755:                   false
URxvt.keysym.Shift-Control-V:     eval:paste_clipboard
URxvt.keysym.Shift-Control-C:     eval:selection_to_clipboard
!Xterm escape codes, word by word movement
URxvt.keysym.Control-Left:        \033[1;5D
URxvt.keysym.Shift-Control-Left:  \033[1;6D
URxvt.keysym.Control-Right:       \033[1;5C
URxvt.keysym.Shift-Control-Right: \033[1;6C
URxvt.keysym.Control-Up:          \033[1;5A
URxvt.keysym.Shift-Control-Up:    \033[1;6A
URxvt.keysym.Control-Down:        \033[1;5B
URxvt.keysym.Shift-Control-Down:  \033[1;6B
URxvt*transparent: true
URxvt*shading: 30
XRESOURCES
}
