#!/bin/bash
declare -A xresources
declare -A i3wm
declare -A polybar
declare -A dunstrc

xresources['background']='#162025'
xresources['foreground']='#bfbfbf'
xresources['cursorcolor']='#bfbfbf'
xresources['color0']='#162025'
xresources['color1']='#393843'
xresources['color2']='#39402e'
xresources['color3']='#39402e'
xresources['color4']='#75404b'
xresources['color5']='#4c584a'
xresources['color6']='#662b37'
xresources['color7']='#bfbfbf'
xresources['color8']='#5d6160'
xresources['color9']='#662b37'
xresources['color10']='#39402e'
xresources['color11']='#39402e'
xresources['color12']='#75404b'
xresources['color13']='#4c584a'
xresources['color14']='#4c584a'
xresources['color15']='#bfbfbf'
xresources['rofi.color-window']='#162025, #39402e, #39402e'
xresources['rofi.color-normal']='#162025, #bfbfbf, #162025, #162025, #75404b'
xresources['rofi.color-active']='#162025, #bfbfbf, #162025, #162025, #75404b'
xresources['rofi.color-urgent']='#162025, #bfbfbf, #162025, #162025, #75404b'

i3wm['client.background']='#162025'
i3wm['client.focused']='#bfbfbf #162025 #bfbfbf #39402e #39402e'
i3wm['client.unfocused']='#bfbfbf #162025 #bfbfbf #75404b #75404b'
i3wm['client.focused_inactive']='#bfbfbf #162025 #bfbfbf #75404b #75404b'
i3wm['client.urgent']='#bfbfbf #162025 #bfbfbf #75404b #75404b'
i3wm['client.placeholder']='#bfbfbf #162025 #bfbfbf #75404b #75404b'

polybar['background']='#162025'
polybar['foreground']='#bfbfbf'
polybar['modules-left']='i3'
polybar['modules-center']='date'
polybar['modules-right']='alsa wlan eth powermenu'
polybar['label-unfocused-background']='#75404b'
polybar['label-unfocused-foreground']='#162025'
polybar['label-mode-background']='#75404b'
polybar['label-mode-foreground']='#162025'
polybar['label-focused-foreground']='#6b7443'
polybar['label-focused-background']='#75404b'
polybar['label-visible-background']='#75404b'
polybar['label-visible-foreground']='#162025'
polybar['format-foreground']='#162025'
polybar['format-background']='#4c584a'
polybar['label-open-foreground']='#39402e'
polybar['label-close-foreground']='#39402e'
polybar['label-separator-foreground']='#39402e'
polybar['format-connected-foreground']='#162025'
polybar['format-connected-background']='#39402e'
polybar['format-connected-prefix-foreground']='#162025'
polybar['ramp-signal-foreground']='#162025'

dunstrc['background']=${polybar['background']}
dunstrc['foreground']=${polybar['format-background']}
dunstrc['frame_color']=${polybar['format-background']}

wallpaper='002.png'
