#!/bin/bash
declare -A xresources
declare -A i3wm
declare -A polybar
declare -A dunstrc

xresources['background']='#162025'
xresources['foreground']='#bfbfbf'
xresources['cursorcolor']='#bfbfbf'
xresources['color0']='#162025'
xresources['color1']='#393843'
xresources['color2']='#193a48'
xresources['color3']='#235964'
xresources['color4']='#193a48'
xresources['color5']='#2a474a'
xresources['color6']='#662b37'
xresources['color7']='#bfbfbf'
xresources['color8']='#365a5c'
xresources['color9']='#662b37'
xresources['color10']='#193a48'
xresources['color11']='#193a48'
xresources['color12']='#75404b'
xresources['color13']='#662b37'
xresources['color14']='#083842'
xresources['color15']='#bfbfbf'
xresources['rofi.color-window']='#162025, #193a48, #193a48'
xresources['rofi.color-normal']='#162025, #bfbfbf, #162025, #162025, #193a48'
xresources['rofi.color-active']='#162025, #bfbfbf, #162025, #162025, #193a48'
xresources['rofi.color-urgent']='#162025, #bfbfbf, #162025, #162025, #193a48'

i3wm['client.background']='#162025'
i3wm['client.focused']='#bfbfbf #162025 #bfbfbf #193a48 #193a48'
i3wm['client.unfocused']='#bfbfbf #162025 #bfbfbf #193a48 #193a48'
i3wm['client.focused_inactive']='#bfbfbf #162025 #bfbfbf #193a48 #193a48'
i3wm['client.urgent']='#bfbfbf #162025 #bfbfbf #193a48 #193a48'
i3wm['client.placeholder']='#bfbfbf #162025 #bfbfbf #193a48 #193a48'

polybar['background']='#162025'
polybar['foreground']='#bfbfbf'
polybar['modules-left']='i3'
polybar['modules-center']='date'
polybar['modules-right']='wlan eth powermenu'
polybar['label-unfocused-background']='#193a48'
polybar['label-unfocused-foreground']='#162025'
polybar['label-mode-background']='#193a48'
polybar['label-mode-foreground']='#162025'
polybar['label-focused-foreground']='#6b7443'
polybar['label-focused-background']='#193a48'
polybar['label-visible-background']='#193a48'
polybar['label-visible-foreground']='#162025'
polybar['format-foreground']='#162025'
polybar['format-background']='#2a474a'
polybar['label-open-foreground']='#193a48'
polybar['label-close-foreground']='#193a48'
polybar['label-separator-foreground']='#193a48'
polybar['format-connected-foreground']='#162025'
polybar['format-connected-background']='#193a48'
polybar['format-connected-prefix-foreground']='#162025'
polybar['ramp-signal-foreground']='#162025'

dunstrc['background']=${polybar['background']}
dunstrc['foreground']=${polybar['format-background']}
dunstrc['frame_color']=${polybar['format-background']}

wallpaper='003.png'
