#!/bin/bash
declare -A xresources
declare -A i3wm
declare -A polybar
declare -A dunstrc

xresources['background']='#1d1e26'
xresources['foreground']='#b0b287'
xresources['cursorcolor']='#b0b287'
xresources['color0']='#1d1e26'
xresources['color1']='#5a6c56'
xresources['color2']='#8c9440'
xresources['color3']='#73908b'
xresources['color4']='#789073'
xresources['color5']='#85678f'
xresources['color6']='#5e8d87'
xresources['color7']='#9297bf'
xresources['color8']='#373b41'
xresources['color9']='#907378'
xresources['color10']='#b5bd68'
xresources['color11']='#f0c674'
xresources['color12']='#789073'
xresources['color13']='#b294bb'
xresources['color14']='#8abeb7'
xresources['color15']='#b0b287'
xresources['rofi.color-window']='#1d1e26, #b5bd68, #b5bd68'
xresources['rofi.color-normal']='#1d1e26, #b0b287, #8c9440, #b0b287, #78824B'
xresources['rofi.color-active']='#1d1e26, #b0b287, #8c9440, #b0b287, #78824B'
xresources['rofi.color-urgent']='#1d1e26, #b0b287, #8c9440, #b0b287, #78824B'

i3wm['client.background']='#1d1e26'
i3wm['client.focused']='#b0b287 #1d1e26 #b0b287 #789073 #789073'
i3wm['client.unfocused']='#b0b287 #1d1e26 #b0b287 #789073 #789073'
i3wm['client.focused_inactive']='#b0b287 #1d1e26 #b0b287 #789073 #789073'
i3wm['client.urgent']='#b0b287 #1d1e26 #b0b287 #789073 #789073'
i3wm['client.placeholder']='#b0b287 #1d1e26 #b0b287 #789073 #789073'

polybar['background']='#1d1e26'
polybar['foreground']='#b0b287'
polybar['modules-left']='wlan eth'
polybar['modules-center']='i3'
polybar['modules-right']='alsa date powermenu'
polybar['label-unfocused-background']='#789073'
polybar['label-unfocused-foreground']='#1d1e26'
polybar['label-mode-background']='#1d1e26'
polybar['label-mode-foreground']='#1d1e26'
polybar['label-focused-foreground']='#ffffff'
polybar['label-focused-background']='#789073'
polybar['label-visible-background']='#789073'
polybar['label-visible-foreground']='#1d1e26'
polybar['format-foreground']='#1d1e26'
polybar['format-background']='#789073'
polybar['label-open-foreground']='#789073'
polybar['label-close-foreground']='#789073'
polybar['label-separator-foreground']='#789073'
polybar['format-connected-foreground']='#1d1e26'
polybar['format-connected-background']='#789073'
polybar['format-connected-prefix-foreground']='#1d1e26'
polybar['ramp-signal-foreground']='#1d1e26'

dunstrc['background']=${polybar['background']}
dunstrc['foreground']=${polybar['format-background']}
dunstrc['frame_color']=${polybar['format-background']}

wallpaper='004.png'
