#!/bin/bash
declare -A xresources
declare -A i3wm
declare -A polybar
declare -A dunstrc

xresources['background']='#2f2f38'
xresources['foreground']='#b0c4bb'
xresources['cursorcolor']='#b0c4bb'
xresources['color0']='#34343e'
xresources['color1']='#9aafaa'
xresources['color2']='#759496'
xresources['color3']='#93b3b0'
xresources['color4']='#688486'
xresources['color5']='#668ca1'
xresources['color6']='#759496'
xresources['color7']='#b0c4bb'
xresources['color8']='#b0c4bb'
xresources['color9']='#9aafaa'
xresources['color10']='#759496'
xresources['color11']='#93b3b0'
xresources['color12']='#81a2be'
xresources['color13']='#668ca1'
xresources['color14']='#759496'
xresources['color15']='#b0c4bb'
xresources['rofi.color-window']='#34343e, #759496, #759496'
xresources['rofi.color-normal']='#34343e, #b0c4bb, #759496, #b0c4bb, #78824B'
xresources['rofi.color-active']='#34343e, #b0c4bb, #759496, #b0c4bb, #78824B'
xresources['rofi.color-urgent']='#34343e, #b0c4bb, #759496, #b0c4bb, #78824B'

i3wm['client.background']='#2f2f38'
i3wm['client.focused']='#b0c4bb #2f2f38 #b0c4bb #81a2be #81a2be'
i3wm['client.unfocused']='#b0c4bb #2f2f38 #b0c4bb #688486 #688486'
i3wm['client.focused_inactive']='#b0c4bb #2f2f38 #b0c4bb #688486 #688486'
i3wm['client.urgent']='#b0c4bb #2f2f38 #b0c4bb #688486 #688486'
i3wm['client.placeholder']='#b0c4bb #2f2f38 #b0c4bb #688486 #688486'

polybar['background']='#2f2f38'
polybar['foreground']='#b0c4bb'
polybar['modules-left']='wlan eth'
polybar['modules-center']='i3'
polybar['modules-right']='date powermenu'
polybar['label-unfocused-background']='#81a2be'
polybar['label-unfocused-foreground']='#2f2f38'
polybar['label-mode-background']='#2f2f38'
polybar['label-mode-foreground']='#34343e'
polybar['label-focused-foreground']='#2f2f38'
polybar['label-focused-background']='#688486'
polybar['label-visible-background']='#81a2be'
polybar['label-visible-foreground']='#2f2f38'
polybar['format-foreground']='#2f2f38'
polybar['format-background']='#81a2be'
polybar['label-open-foreground']='#81a2be'
polybar['label-close-foreground']='#81a2be'
polybar['label-separator-foreground']='#81a2be'
polybar['format-connected-foreground']='#2f2f38'
polybar['format-connected-background']='#81a2be'
polybar['format-connected-prefix-foreground']='#2f2f38'
polybar['ramp-signal-foreground']='#2f2f38'

dunstrc['background']=${polybar['background']}
dunstrc['foreground']=${polybar['format-background']}
dunstrc['frame_color']=${polybar['format-background']}

wallpaper='005.png'
