#!/bin/bash
declare -A xresources
declare -A i3wm
declare -A polybar
declare -A dunstrc

xresources['background']='#1f1f1f'
xresources['foreground']='#c6c6c6'
xresources['cursorcolor']='#c6c6c6'
xresources['color0']='#828282'
xresources['color8']='#828282'
xresources['color1']='#cc6666'
xresources['color9']='#cc6666'
xresources['color2']='#8abeb7'
xresources['color10']='#8abeb7'
xresources['color3']='#f0c674'
xresources['color11']='#f0c674'
xresources['color4']='#8abeb7'
xresources['color12']='#8abeb7'
xresources['color5']='#b294bb'
xresources['color13']='#b294bb'
xresources['color6']='#8abeb7'
xresources['color14']='#8abeb7'
xresources['color7']='#828282'
xresources['color15']='#c6c6c6'
xresources['rofi.color-window']='#828282, #8abeb7, #8abeb7'
xresources['rofi.color-normal']='#828282, #c6c6c6, #8abeb7, #c6c6c6, #78824B'
xresources['rofi.color-active']='#828282, #c6c6c6, #8abeb7, #c6c6c6, #78824B'
xresources['rofi.color-urgent']='#828282, #c6c6c6, #8abeb7, #c6c6c6, #78824B'

i3wm['client.background']='#1f1f1f'
i3wm['client.focused']='#c6c6c6 #1f1f1f #c6c6c6 #8abeb7 #8abeb7'
i3wm['client.unfocused']='#c6c6c6 #1f1f1f #c6c6c6 #8abeb7 #8abeb7'
i3wm['client.focused_inactive']='#c6c6c6 #1f1f1f #c6c6c6 #8abeb7 #8abeb7'
i3wm['client.urgent']='#c6c6c6 #1f1f1f #c6c6c6 #8abeb7 #8abeb7'
i3wm['client.placeholder']='#c6c6c6 #1f1f1f #c6c6c6 #8abeb7 #8abeb7'

polybar['background']='#1f1f1f'
polybar['foreground']='#c6c6c6'
polybar['modules-left']='wlan eth'
polybar['modules-center']='i3'
polybar['modules-right']='alsa date powermenu'
polybar['label-unfocused-background']='#8abeb7'
polybar['label-unfocused-foreground']='#1f1f1f'
polybar['label-mode-background']='#1f1f1f'
polybar['label-mode-foreground']='#828282'
polybar['label-focused-foreground']='#1f1f1f'
polybar['label-focused-background']='#5A9B92'
polybar['label-visible-background']='#8abeb7'
polybar['label-visible-foreground']='#1f1f1f'
polybar['format-foreground']='#1f1f1f'
polybar['format-background']='#8abeb7'
polybar['label-open-foreground']='#8abeb7'
polybar['label-close-foreground']='#8abeb7'
polybar['label-separator-foreground']='#8abeb7'
polybar['format-connected-foreground']='#1f1f1f'
polybar['format-connected-background']='#8abeb7'
polybar['format-connected-prefix-foreground']='#1f1f1f'
polybar['ramp-signal-foreground']='#1f1f1f'

dunstrc['background']=${polybar['background']}
dunstrc['foreground']=${polybar['format-background']}
dunstrc['frame_color']=${polybar['format-background']}

wallpaper='007.png'
