#!/bin/bash
declare -A xresources
declare -A i3wm
declare -A polybar
declare -A dunstrc

xresources['background']='#131822'
xresources['foreground']='#aab0bc'
xresources['cursorcolor']='#aab0bc'
xresources['color0']='#131822'
xresources['color1']='#7b8ba3'
xresources['color2']='#657893'
xresources['color3']='#4e6584'
xresources['color4']='#233f66'
xresources['color5']='#1c3251'
xresources['color6']='#15253d'
xresources['color7']='#aab0bc'
xresources['color8']='#626975'
xresources['color9']='#7b8ba3'
xresources['color10']='#657893'
xresources['color11']='#4e6584'
xresources['color12']='#233f66'
xresources['color13']='#1c3251'
xresources['color14']='#15253d'
xresources['color15']='#aab0bc'
xresources['rofi.color-window']='#131822, #233f66, #233f66'
xresources['rofi.color-normal']='#131822, #aab0bc, #233f66, #aab0bc, #78824B'
xresources['rofi.color-active']='#131822, #aab0bc, #233f66, #aab0bc, #78824B'
xresources['rofi.color-urgent']='#131822, #aab0bc, #233f66, #aab0bc, #78824B'

i3wm['client.background']='#131822'
i3wm['client.focused']='#aab0bc #131822 #aab0bc #233f66 #233f66'
i3wm['client.unfocused']='#aab0bc #131822 #aab0bc #233f66 #233f66'
i3wm['client.focused_inactive']='#aab0bc #131822 #aab0bc #233f66 #233f66'
i3wm['client.urgent']='#aab0bc #131822 #aab0bc #233f66 #233f66'
i3wm['client.placeholder']='#aab0bc #131822 #aab0bc #233f66 #233f66'

polybar['background']='#131822'
polybar['foreground']='#aab0bc'
polybar['modules-left']='wlan eth'
polybar['modules-center']='i3'
polybar['modules-right']='date powermenu'
polybar['label-unfocused-background']='#233f66'
polybar['label-unfocused-foreground']='#131822'
polybar['label-mode-background']='#131822'
polybar['label-mode-foreground']='#131822'
polybar['label-focused-foreground']='#131822'
polybar['label-focused-background']='#233f66'
polybar['label-visible-background']='#233f66'
polybar['label-visible-foreground']='#131822'
polybar['format-foreground']='#131822'
polybar['format-background']='#233f66'
polybar['label-open-foreground']='#233f66'
polybar['label-close-foreground']='#233f66'
polybar['label-separator-foreground']='#233f66'
polybar['format-connected-foreground']='#131822'
polybar['format-connected-background']='#233f66'
polybar['format-connected-prefix-foreground']='#131822'
polybar['ramp-signal-foreground']='#131822'

dunstrc['background']=${polybar['background']}
dunstrc['foreground']=${polybar['format-background']}
dunstrc['frame_color']=${polybar['format-background']}

wallpaper='008.png'
