#!/bin/bash
declare -A xresources
declare -A i3wm
declare -A polybar
declare -A dunstrc

xresources['background']='#1d1f21'
xresources['foreground']='#707880'
xresources['cursorcolor']='#707880'
xresources['color0']='#282a2e'
xresources['color1']='#a54242'
xresources['color2']='#8c9440'
xresources['color3']='#de935f'
xresources['color4']='#5f819d'
xresources['color5']='#85678f'
xresources['color6']='#5e8d87'
xresources['color7']='#707880'
xresources['color8']='#373b41'
xresources['color9']='#cc6666'
xresources['color10']='#707880'
xresources['color11']='#f0c674'
xresources['color12']='#5f819d'
xresources['color13']='#b294bb'
xresources['color14']='#8abeb7'
xresources['color15']='#c5c8c6'
xresources['rofi.color-window']='#1d1f21, #8c9440, #8c9440'
xresources['rofi.color-normal']='#1d1f21, #707880, #1d1f21, #1d1f21, #5f819d'
xresources['rofi.color-active']='#1d1f21, #707880, #1d1f21, #1d1f21, #5f819d'
xresources['rofi.color-urgent']='#1d1f21, #707880, #1d1f21, #1d1f21, #5f819d'

i3wm['client.background']='#1d1f21'
i3wm['client.focused']='#707880 #1d1f21 #707880 #8c9440 #8c9440'
i3wm['client.unfocused']='#707880 #1d1f21 #707880 #5f819d #5f819d'
i3wm['client.focused_inactive']='#707880 #1d1f21 #707880 #5f819d #5f819d'
i3wm['client.urgent']='#707880 #1d1f21 #707880 #5f819d #5f819d'
i3wm['client.placeholder']='#707880 #1d1f21 #707880 #5f819d #5f819d'

polybar['background']='#1d1f21'
polybar['foreground']='#c5c8c6'
polybar['modules-left']='i3'
polybar['modules-center']='date'
polybar['modules-right']='wlan eth powermenu'
polybar['label-unfocused-background']='#282a2e'
polybar['label-unfocused-foreground']='#c5c8c6'
polybar['label-mode-background']='#282a2e'
polybar['label-mode-foreground']='#c5c8c6'
polybar['label-focused-foreground']='#6b7443'
polybar['label-focused-background']='#373b41'
polybar['label-visible-background']='#282a2e'
polybar['label-visible-foreground']='#c5c8c6'
polybar['format-foreground']='#c5c8c6'
polybar['format-background']='#282a2e'
polybar['label-open-foreground']='#c5c8c6'
polybar['label-close-foreground']='#c5c8c6'
polybar['label-separator-foreground']='#c5c8c6'
polybar['format-connected-foreground']='#c5c8c6'
polybar['format-connected-background']='#282a2e'
polybar['format-connected-prefix-foreground']='#c5c8c6'
polybar['ramp-signal-foreground']='#c5c8c6'

dunstrc['background']=${polybar['background']}
dunstrc['foreground']=${polybar['format-background']}
dunstrc['frame_color']=${polybar['format-background']}

wallpaper='010.png'
