#!/bin/bash
declare -A xresources
declare -A i3wm
declare -A polybar
declare -A dunstrc

xresources['background']='#1e1e20'
xresources['foreground']='#c5c8c6'
xresources['cursorcolor']='#c5c8c6'
xresources['color0']='#1e1e20'
xresources['color1']='#e6a57a'
xresources['color2']='#e39866'
xresources['color3']='#df8b54'
xresources['color4']='#dc7f41'
xresources['color5']='#85678f'
xresources['color6']='#b06534'
xresources['color7']='#f1cbb3'
xresources['color8']='#f4d8c6'
xresources['color9']='#e6a57a'
xresources['color10']='#e39866'
xresources['color11']='#df8b54'
xresources['color12']='#dc7f41'
xresources['color13']='#c6723a'
xresources['color14']='#b06534'
xresources['color15']='#f1cbb3'
xresources['rofi.color-window']='#1e1e20, #dc7f41, #dc7f41'
xresources['rofi.color-normal']='#1e1e20, #c5c8c6, #1e1e20, #1e1e20, #dc7f41'
xresources['rofi.color-active']='#1e1e20, #c5c8c6, #1e1e20, #1e1e20, #dc7f41'
xresources['rofi.color-urgent']='#1e1e20, #c5c8c6, #1e1e20, #1e1e20, #dc7f41'

i3wm['client.background']='#1e1e20'
i3wm['client.focused']='#e39866 #1e1e20 #e39866 #e39866 #e39866'
i3wm['client.unfocused']='#e39866 #1e1e20 #e39866 #dc7f41 #dc7f41'
i3wm['client.focused_inactive']='#e39866 #1e1e20 #e39866 #dc7f41 #dc7f41'
i3wm['client.urgent']='#e39866 #1e1e20 #e39866 #dc7f41 #dc7f41'
i3wm['client.placeholder']='#e39866 #1e1e20 #e39866 #dc7f41 #dc7f41'

polybar['background']='#1e1e20'
polybar['foreground']='#c5c8c6'
polybar['modules-left']='i3'
polybar['modules-center']='date'
polybar['modules-right']='wlan eth powermenu'
polybar['label-unfocused-background']='#e39866'
polybar['label-unfocused-foreground']='#1e1e20'
polybar['label-mode-background']='#e39866'
polybar['label-mode-foreground']='#1e1e20'
polybar['label-focused-foreground']='#6b7443'
polybar['label-focused-background']='#dc7f41'
polybar['label-visible-background']='#e39866'
polybar['label-visible-foreground']='#1e1e20'
polybar['format-foreground']='#1e1e20'
polybar['format-background']='#c6723a'
polybar['label-open-foreground']='#e39866'
polybar['label-close-foreground']='#e39866'
polybar['label-separator-foreground']='#e6a57a'
polybar['format-connected-foreground']='#e6a57a'
polybar['format-connected-background']='#1e1e20'
polybar['format-connected-prefix-foreground']='#e6a57a'
polybar['ramp-signal-foreground']='#1e1e20'

dunstrc['background']=${polybar['background']}
dunstrc['foreground']=${polybar['format-background']}
dunstrc['frame_color']=${polybar['format-background']}

wallpaper='011.png'
