#!/bin/bash
declare -A xresources
declare -A i3wm
declare -A polybar
declare -A dunstrc

xresources['background']='#1e1e20'
xresources['foreground']='#c5c8c6'
xresources['cursorcolor']='#c5c8c6'
xresources['color0']='#1e1e20'
xresources['color1']='#80969b'
xresources['color2']='#56737a'
xresources['color3']='#416269'
xresources['color4']='#2c5159'
xresources['color5']='#274850'
xresources['color6']='#1e383e'
xresources['color7']='#a1abad'
xresources['color8']='#a1abad'
xresources['color9']='#80969b'
xresources['color10']='#56737a'
xresources['color11']='#416269'
xresources['color12']='#2c5159'
xresources['color13']='#274850'
xresources['color14']='#1e383e'
xresources['color15']='#a1abad'
xresources['rofi.color-window']='#1e1e20, #2c5159, #2c5159'
xresources['rofi.color-normal']='#1e1e20, #c5c8c6, #1e1e20, #1e1e20, #2c5159'
xresources['rofi.color-active']='#1e1e20, #c5c8c6, #1e1e20, #1e1e20, #2c5159'
xresources['rofi.color-urgent']='#1e1e20, #c5c8c6, #1e1e20, #1e1e20, #2c5159'

i3wm['client.background']='#1e1e20'
i3wm['client.focused']='#56737a #1e1e20 #56737a #56737a #56737a'
i3wm['client.unfocused']='#56737a #1e1e20 #56737a #2c5159 #2c5159'
i3wm['client.focused_inactive']='#56737a #1e1e20 #56737a #2c5159 #2c5159'
i3wm['client.urgent']='#56737a #1e1e20 #56737a #2c5159 #2c5159'
i3wm['client.placeholder']='#56737a #1e1e20 #56737a #2c5159 #2c5159'

polybar['background']='#1e1e20'
polybar['foreground']='#c5c8c6'
polybar['modules-left']='i3'
polybar['modules-center']='date'
polybar['modules-right']='alsa wlan eth powermenu'
polybar['label-unfocused-background']='#56737a'
polybar['label-unfocused-foreground']='#1e1e20'
polybar['label-mode-background']='#56737a'
polybar['label-mode-foreground']='#1e1e20'
polybar['label-focused-foreground']='#6b7443'
polybar['label-focused-background']='#2c5159'
polybar['label-visible-background']='#56737a'
polybar['label-visible-foreground']='#1e1e20'
polybar['format-foreground']='#1e1e20'
polybar['format-background']='#416269'
polybar['label-open-foreground']='#56737a'
polybar['label-close-foreground']='#56737a'
polybar['label-separator-foreground']='#80969b'
polybar['format-connected-foreground']='#80969b'
polybar['format-connected-background']='#1e1e20'
polybar['format-connected-prefix-foreground']='#80969b'
polybar['ramp-signal-foreground']='#1e1e20'

dunstrc['background']=${polybar['background']}
dunstrc['foreground']=${polybar['format-background']}
dunstrc['frame_color']=${polybar['format-background']}

wallpaper='013.png'
