#!/bin/bash
declare -A xresources
declare -A i3wm
declare -A polybar
declare -A dunstrc

xresources['color0']='#040305' # Terminal background color
xresources['color1']='#7096a9' # git commit color
xresources['color2']='#e3e1e7' # polybar right color
xresources['color3']='#97ad79' # window border color 97ad79
xresources['color4']='#655870' # polybar left color
xresources['color5']='#8c7e99' # 
xresources['color6']='#b5acbe' #  
xresources['color7']='#b76988' # dunst border color
xresources['color8']='#c89a6e' # 
xresources['color9']='#b693d3' #
xresources['color10']='#b76988' #
xresources['color11']='#c0a7d7' #
xresources['color12']='#628f83' # polybar left color
xresources['color13']='#97ad79' # polybar center color and dunst primary color
xresources['color14']='#86b1a5'
xresources['color15']='#7096a9' # terminal font color
xresources['background']=${xresources['color0']}
xresources['foreground']=${xresources['color7']}
xresources['cursorcolor']=${xresources['color7']}
xresources['rofi.color-window']="${xresources['color0']}, ${xresources['color2']}, ${xresources['color2']}"
xresources['rofi.color-normal']="${xresources['color0']}, ${xresources['color7']}, ${xresources['color0']}, ${xresources['color0']}, ${xresources['color4']}"
xresources['rofi.color-active']="${xresources['color0']}, ${xresources['color7']}, ${xresources['color0']}, ${xresources['color0']}, ${xresources['color4']}"
xresources['rofi.color-urgent']="${xresources['color0']}, ${xresources['color7']}, ${xresources['color0']}, ${xresources['color0']}, ${xresources['color4']}"

i3wm['client.background']=${xresources['color0']}
i3wm['client.focused']="${xresources['color7']} ${xresources['color0']} ${xresources['color7']} ${xresources['color2']} ${xresources['color2']}"
i3wm['client.unfocused']="${xresources['color7']} ${xresources['color0']} ${xresources['color7']} ${xresources['color4']}"
i3wm['client.focused_inactive']="${xresources['color7']} ${xresources['color0']} ${xresources['color7']} ${xresources['color4']} ${xresources['color4']}"
i3wm['client.urgent']="${xresources['color7']} ${xresources['color0']} ${xresources['color7']} ${xresources['color4']} ${xresources['color4']}"
i3wm['client.placeholder']="${xresources['color7']} ${xresources['color0']} ${xresources['color0']} ${xresources['color4']} ${xresources['color4']}"

polybar['background']=${xresources['color0']}
polybar['foreground']=${xresources['color7']}
polybar['modules-left']='i3'
polybar['modules-center']='date'
polybar['modules-right']='wlan eth powermenu'
polybar['label-unfocused-background']=${xresources['color4']}
polybar['label-unfocused-foreground']=${xresources['color0']}
polybar['label-mode-background']=${xresources['color4']}
polybar['label-mode-foreground']=${xresources['color0']}
polybar['label-focused-foreground']='#6B7443'
polybar['label-focused-background']=${xresources['color4']}
polybar['label-visible-background']=${xresources['color4']}
polybar['label-visible-foreground']=${xresources['color0']}
polybar['format-foreground']=${xresources['color0']}
polybar['format-background']=${xresources['color5']}
polybar['label-open-foreground']=${xresources['color2']}
polybar['label-close-foreground']=${xresources['color2']}
polybar['label-separator-foreground']=${xresources['color2']}
polybar['format-connected-foreground']=${xresources['color0']}
polybar['format-connected-background']=${xresources['color2']}
polybar['format-connected-prefix-foreground']=${xresources['color0']}
polybar['ramp-signal-foreground']=${xresources['color0']}

dunstrc['background']=${polybar['background']}
dunstrc['foreground']=${polybar['foreground']}
dunstrc['frame_color']=${polybar['foreground']}

wallpaper='014.jpg'
