#!/bin/bash
declare -A xresources
declare -A i3wm
declare -A polybar
declare -A dunstrc

xresources['background']='#212121'
xresources['foreground']='#FFFFFF'
xresources['cursorcolor']=${xresources['foreground']}
xresources['color0']=${xresources['background']}
xresources['color8']=${xresources['foreground']}
xresources['color1']=''
xresources['color9']=${xresources['color1']}
xresources['color2']=''
xresources['color10']=${xresources['color2']}
xresources['color3']=${xresources['color2']}
xresources['color11']=${xresources['color2']}
xresources['color4']=''
xresources['color12']=${xresources['color4']}
xresources['color5']=''
xresources['color13']=${xresources['color5']}
xresources['color6']=''
xresources['color14']=${xresources['color6']}
xresources['color7']=''
xresources['color15']=${xresources['color7']}
xresources['rofi.color-window']="${xresources['color0']}, ${xresources['color2']}, ${xresources['color2']}"
xresources['rofi.color-normal']="${xresources['color0']}, ${xresources['color7']}, ${xresources['color0']}, ${xresources['color0']}, ${xresources['color4']}"
xresources['rofi.color-active']="${xresources['color0']}, ${xresources['color7']}, ${xresources['color0']}, ${xresources['color0']}, ${xresources['color4']}"
xresources['rofi.color-urgent']="${xresources['color0']}, ${xresources['color7']}, ${xresources['color0']}, ${xresources['color0']}, ${xresources['color4']}"

i3wm['client.background']=${xresources['color0']}
i3wm['client.focused']="${xresources['color7']} ${xresources['color0']} ${xresources['color7']} ${xresources['color2']} ${xresources['color2']}"
i3wm['client.unfocused']="${xresources['color7']} ${xresources['color0']} ${xresources['color7']} ${xresources['color4']}"
i3wm['client.focused_inactive']="${xresources['color7']} ${xresources['color0']} ${xresources['color7']} ${xresources['color4']} ${xresources['color4']}"
i3wm['client.urgent']="${xresources['color7']} ${xresources['color0']} ${xresources['color7']} ${xresources['color4']} ${xresources['color4']}"
i3wm['client.placeholder']="${xresources['color7']} ${xresources['color0']} ${xresources['color0']} ${xresources['color4']} ${xresources['color4']}"

polybar['background']=${xresources['color0']}
polybar['foreground']=${xresources['color7']}
polybar['modules-left']='i3'
polybar['modules-center']='date'
polybar['modules-right']='wlan eth powermenu'
polybar['label-unfocused-background']=${xresources['color4']}
polybar['label-unfocused-foreground']=${xresources['color0']}
polybar['label-mode-background']=${xresources['color4']}
polybar['label-mode-foreground']=${xresources['color0']}
polybar['label-focused-foreground']='#6B7443'
polybar['label-focused-background']=${xresources['color4']}
polybar['label-visible-background']=${xresources['color4']}
polybar['label-visible-foreground']=${xresources['color0']}
polybar['format-foreground']=${xresources['color0']}
polybar['format-background']=${xresources['color5']}
polybar['label-open-foreground']=${xresources['color2']}
polybar['label-close-foreground']=${xresources['color2']}
polybar['label-separator-foreground']=${xresources['color2']}
polybar['format-connected-foreground']=${xresources['color0']}
polybar['format-connected-background']=${xresources['color2']}
polybar['format-connected-prefix-foreground']=${xresources['color0']}
polybar['ramp-signal-foreground']=${xresources['color0']}

dunstrc['background']=${polybar['background']}
dunstrc['foreground']=${polybar['foreground']}
dunstrc['frame_color']=${polybar['foreground']}

wallpaper='000.png'
